apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: the-project-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tripplen23/dwk-config.git
    targetRevision: ">=4.10.0"
    path: overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true