apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
- ../../base
patches:
- path: broadcaster.yaml
- path: deployment.yaml
images:
- name: PROJECT/BROADCASTER
  newName: europe-north1-docker.pkg.dev/dwk-gke-506208/my-repository/broadcaster
  newTag: 6c133ba94e1f29dc7ed51234bba3b9e0a885c22c
- name: PROJECT/CHAT-SINK
  newName: europe-north1-docker.pkg.dev/dwk-gke-506208/my-repository/chat-sink
  newTag: 6c133ba94e1f29dc7ed51234bba3b9e0a885c22c
- name: PROJECT/TODO-APP
  newName: europe-north1-docker.pkg.dev/dwk-gke-506208/my-repository/todo-app
  newTag: 6c133ba94e1f29dc7ed51234bba3b9e0a885c22c
- name: PROJECT/TODO-BACKEND
  newName: europe-north1-docker.pkg.dev/dwk-gke-506208/my-repository/todo-backend
  newTag: 6c133ba94e1f29dc7ed51234bba3b9e0a885c22c
