apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
- ../../base
patches:
- path: broadcaster.yaml
- path: deployment.yaml
images:
- name: PROJECT/BROADCASTER
  newName: europe-north1-docker.pkg.dev/dwk-gke-506208/my-repository/broadcaster
  newTag: a135001a949a3366222ada311a5f069744d82af4
- name: PROJECT/CHAT-SINK
  newName: europe-north1-docker.pkg.dev/dwk-gke-506208/my-repository/chat-sink
  newTag: a135001a949a3366222ada311a5f069744d82af4
- name: PROJECT/TODO-APP
  newName: europe-north1-docker.pkg.dev/dwk-gke-506208/my-repository/todo-app
  newTag: a135001a949a3366222ada311a5f069744d82af4
- name: PROJECT/TODO-BACKEND
  newName: europe-north1-docker.pkg.dev/dwk-gke-506208/my-repository/todo-backend
  newTag: a135001a949a3366222ada311a5f069744d82af4
